apiVersion: v1
kind: Service
metadata:
  name: mysite-service
  namespace: mysite
spec:
  type: NodePort
  selector:
    app: mysite
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
